### ISSUE TITLE
app.js 500 Internal Server Error

### ISSUE THREAD

**Issue by mstiv** [Blockstream/esplora#104]
Hello!

Ubuntu 16.04.6 LTS
npm 6.9.0
node v10.16.0

SyntaxError: /home/esplora/esplora/client/src/views/home.js: Unexpected token (10:2)
   8 |
   9 | const homeLayout = (body, { t, activeTab, ...S }) => layout(
> 10 |   <div>
     |   ^
  11 |     <div className="jumbotron jumbotron-fluid">
  12 |       <div className="explorer-title-container">
  13 |         <img className="explorer-title-container_logo" alt="" src={`${staticRoot}img/icons/menu-logo.svg`} />
    at Parser.pp$5.raise (/home/esplora/esplora/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/esplora/esplora/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/home/esplora/esplora/node_modules/babylon/lib/index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (/home/esplora/esplora/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/home/esplora/esplora/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/home/esplora/esplora/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/home/esplora/esplora/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/home/esplora/esplora/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExprListItem (/home/esplora/esplora/node_modules/babylon/lib/index.js:4312:16)
    at Parser.pp$3.parseCallExpressionArguments (/home/esplora/esplora/node_modules/babylon/lib/index.js:3573:

**Comment by shesek** [comment]
What did you run/do to receive this error?

**Comment by mstiv** [comment]
Thank you for prompt response. 
# npm run dev-server

**Comment by shesek** [comment]
Which version of nodejs are you using? Did you run `npm install` first?

**Comment by mstiv** [comment]
>  Did you run npm install first?
Yes of course

> Which version of nodejs are you using?
stable version node v10.16.0

**Comment by shesek** [comment]
Can you try running `npm install` inside the `client` directory too?

Can you check if `npm run dist` works?

**Comment by shesek** [comment]
Ping @mstiv, I'm closing for now. Please report back if you're still having issues and I'll re-open.

**Comment by chagelstein** [comment]
Hi @shesek I followed your instructions but got the following:
> esplora-client@0.1.0 postinstall
> ../node_modules/.bin/patch-package

'..' is not recognized as an internal or external command,
operable program or batch file.
npm error code 1
npm error path C:\Users\Alice\esplora\client
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c ../node_modules/.bin/patch-package
npm error A complete log of this run can be found in: C:\Users\Alice\AppData\Local\npm-cache\_logs\2024-10-12T09_32_08_649Z-debug-0.log
[_2024-10-12T09_32_08_649Z-debug-0.log](https://github.com/user-attachments/files/17349538/_2024-10-12T09_32_08_649Z-debug-0.log)

**Comment by shesek** [comment]
Esplora is not actively developed/tested on Windows and likely not working there. Can you try with Linux?
