### ISSUE TITLE
npm install   on centos get many errors

### ISSUE THREAD

**Issue by kolvin2016** [Blockstream/esplora#121]
GET / 304 48.825 ms - -
GET /bootstrap.min.css 304 22.220 ms - -
GET /style.css 304 22.071 ms - -
GET /app.js 500 1.924 ms - 762
Error: Cannot find module 'browserify-package-json' from '/root/esplora/client'
    at /root/esplora/node_modules/resolve/lib/async.js:68:35
    at processDirs (/root/esplora/node_modules/resolve/lib/async.js:208:39)
    at ondir (/root/esplora/node_modules/resolve/lib/async.js:223:13)
    at load (/root/esplora/node_modules/resolve/lib/async.js:101:43)
    at onex (/root/esplora/node_modules/resolve/lib/async.js:126:17)
    at /root/esplora/node_modules/resolve/lib/async.js:13:69
    at FSReqWrap.oncomplete (fs.js:154:21)
GET /font/inconsolata/index.css 304 0.234 ms - -
GET /light-theme_style.css 304 0.181 ms - -
GET /img/icons/plus.png 304 0.231 ms - -
GET /img/icons/arrow_right_blu.png 304 0.210 ms - -
GET /img/icons/arrow_left_blu.png 304 0.224 ms - -
GET /img/icons/copy.png 304 0.144 ms - -
GET /img/icons/menu-logo.png 304 0.229 ms - -
GET /img/Loading.gif 304 0.224 ms - -
GET /font/DINPro-Regular.otf 304 0.219 ms - -
GET /img/icons/search.png 304 0.201 ms - -
GET /img/favicon.png 200 0.825 ms - 2092

please tell me which version of node i should to use

**Comment by shesek** [comment]
The recommended node version is 8.

Did you successfully run `npm install` in the main directory? Were the any errors during the installation?

**Comment by antonio-fr** [comment]
Did you npm install as a root user?

**Comment by shesek** [comment]
`npm install` should not require root permissions.

**Comment by antonio-fr** [comment]
The error looks exactly like when you run npm as root (without allowroot and others flags), because the source of the issue is the postinstall script is failling. Hence my question.
