### ISSUE TITLE
'import' and 'export' may appear only with 'sourceType: module' (1:0) while parsing /work/esplora/client/src/run-browser.js while parsing file: /work/esplora/client/src/run-browser.js

### ISSUE THREAD

**Issue by kolvin2016** [Blockstream/esplora#155]
use command: npm run dev-server get error:
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0) while parsing /work/esplora/client/src/run-browser.js while parsing file: /work/esplora/client/src/run-browser.js
    at DestroyableTransform.end [as _flush] (/work/esplora/node_modules/insert-module-globals/index.js:114:21)
    at DestroyableTransform.prefinish (/work/esplora/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at emitNone (events.js:106:13)
    at DestroyableTransform.emit (events.js:208:7)
    at prefinish (/work/esplora/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (/work/esplora/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (/work/esplora/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (/work/esplora/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at PassThrough.onend (_stream_readable.js:595:10)
    at Object.onceWrapper (events.js:313:30)

**Comment by shesek** [comment]
Which version of nodejs are you running? Try using nodejs v8 or newer.

**Comment by shesek** [comment]
Closing for now, please report back if you're still having issues with nodejs v8.
