### ISSUE TITLE
Install failing, fresh Ubuntu 20.04, and npm

### ISSUE THREAD

**Issue by arcbtc** [Blockstream/esplora#254]
Following these instructions https://github.com/Blockstream/esplora#developing, the install fails
```
arcbtc@arcbtc:~$ git clone https://github.com/Blockstream/esplora && cd esplora
Cloning into 'esplora'...
remote: Enumerating objects: 55, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 4819 (delta 23), reused 31 (delta 12), pack-reused 4764
Receiving objects: 100% (4819/4819), 3.03 MiB | 1.00 MiB/s, done.
Resolving deltas: 100% (3411/3411), done.
arcbtc@arcbtc:~/esplora$ npm install

> core-js@3.6.4 postinstall /home/arcbtc/esplora/node_modules/@babel/node/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> esplora@0.1.0 postinstall /home/arcbtc/esplora
> (cd client && npm install) && (cd prerender-server && npm install)


> core-js@2.6.11 postinstall /home/arcbtc/esplora/client/node_modules/@babel/polyfill/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> esplora-client@0.1.0 postinstall /home/arcbtc/esplora/client
> ../node_modules/.bin/patch-package

patch-package 6.2.1
Applying patches...
@cycle/history@7.4.0 ✔
snabbdom-pragma@2.8.0 ✔
npm WARN esplora-client@0.1.0 No description
npm WARN esplora-client@0.1.0 No repository field.

added 198 packages from 219 contributors and audited 198 packages in 7.516s

8 packages are looking for funding
  run `npm fund` for details

found 8 vulnerabilities (7 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN esplora-serverside-render@0.1.0 No description
npm WARN esplora-serverside-render@0.1.0 No repository field.

added 44 packages from 36 contributors and audited 44 packages in 0.998s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm WARN esplora@0.1.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 675 packages from 335 contributors and audited 744 packages in 21.657s

18 packages are looking for funding
  run `npm fund` for details

found 405 vulnerabilities (399 low, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details
arcbtc@arcbtc:~/esplora$ export API_URL=https://blockstream.info/api/
arcbtc@arcbtc:~/esplora$ npm run dev-server

> esplora@0.1.0 dev-server /home/arcbtc/esplora
> babel-node dev-server.js

Browserslist: caniuse-lite is outdated. Please run the following command: `npx browserslist --update-db`
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/arcbtc/esplora/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/arcbtc/esplora/dev-server.js:71:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (/home/arcbtc/esplora/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/home/arcbtc/esplora/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
Emitted 'error' event at:
    at emitErrorNT (net.js:1307:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at Object.<anonymous> (/home/arcbtc/esplora/node_modules/@babel/node/lib/_babel-node.js:180:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! esplora@0.1.0 dev-server: `babel-node dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the esplora@0.1.0 dev-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arcbtc/.npm/_logs/2020-09-08T10_56_32_953Z-debug.log
arcbtc@arcbtc:~/esplora$ 
```
The error log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev-server' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'predev-server', 'dev-server', 'postdev-server' ]
5 info lifecycle esplora@0.1.0~predev-server: esplora@0.1.0
6 info lifecycle esplora@0.1.0~dev-server: esplora@0.1.0
7 verbose lifecycle esplora@0.1.0~dev-server: unsafe-perm in lifecycle true
8 verbose lifecycle esplora@0.1.0~dev-server: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/arcbtc/esplora/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:>
9 verbose lifecycle esplora@0.1.0~dev-server: CWD: /home/arcbtc/esplora
10 silly lifecycle esplora@0.1.0~dev-server: Args: [ '-c', 'babel-node dev-server.js' ]
11 silly lifecycle esplora@0.1.0~dev-server: Returned: code: 1  signal: null
12 info lifecycle esplora@0.1.0~dev-server: Failed to exec dev-server script
13 verbose stack Error: esplora@0.1.0 dev-server: `babel-node dev-server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid esplora@0.1.0
15 verbose cwd /home/arcbtc/esplora
16 verbose Linux 5.4.0-45-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev-server"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error esplora@0.1.0 dev-server: `babel-node dev-server.js`
22 error Exit status 1
23 error Failed at the esplora@0.1.0 dev-server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by shesek** [comment]
It looks like the installation worked, its `npm run dev-server` that failed.

The error message indicates that port 5000 is already used by another program: `Error: listen EADDRINUSE: address already in use :::5000`

Can you try setting a different one with `export PORT=<some port>`?
