### ISSUE TITLE
Electrs: Running with Elements Core:0.18.1.12 on liquidtestnet it panics

### ISSUE THREAD

**Issue by tiero** [Blockstream/esplora#341]
I am running Elements Core:0.18.1.12 on the new `liquidtestnet` and the latest master of electrs-fork (built as docker image from this  [Dockerfile](https://github.com/vulpemventures/docker-electrs/blob/master/abfbce73eb0504630a09f1e6599114ef4fa25bda/Dockerfile.liquid)).

Elements can sync liquidtestnet without problems

## elements.conf

```sh
chain=liquidtestnet
listen=1
txindex=1
# Liquid Testnet (liquidtestnet) settings:
[liquidtestnet]
port=18886

# General settings:
validatepegin=0
anyonecanspendaremine=0
initialfreecoins=2100000000000000
con_dyna_deploy_start=0
con_max_block_sig_size=150
connect=xxx
connect=yyy
fallbackfee=0.00000100


con_has_parent_chain=0
parentgenesisblockhash=NULL
pubkeyprefix=36
scriptprefix=19
blindedprefix=23
bech32_hrp=tex
blech32_hrp=tlq
pchmessagestart=410edd62
dynamic_epoch_length=1000
signblockscript=51210217e403ddb181872c32a0cd468c710040b2f53d8cac69f18dad07985ee37e9a7151ae

```

## compose

```yaml
version: '3.7'
services:
 
  liquid:
    image: ghcr.io/vulpemventures/elements:latest
    container_name: liquid
    command:
      - -datadir=config
    ports:
      - 18884:18884
      - 18886:18886
    volumes:
      - ./volumes/elements/:/config
    restart: unless-stopped


  electrs-liquid:
    image: ghcr.io/vulpemventures/electrs-liquid:latest
    container_name: electrs-liquid
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --parent-network
      - regtest
      - --network
      - liquidtestnet
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - liquid:18884
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:30001
      - --electrum-rpc-addr
      - 0.0.0.0:50001
      - --cors
      - "*"
    environment:
      RUST_BACKTRACE: 1
    depends_on:
      - liquid
    ports:
      - 50001:50001
      - 30001:30001
    volumes:
      - ./volumes/elements/:/config
    restart: unless-stopped
```

## `liquidtestnet`

This gives me the following error

```sh
┗╸❯❯❯ docker logs electrs-liquid                                                                                                
thread 'main' panicked at 'unsupported Bitcoin network: "liquidtestnet"', src/chain.rs:118:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:435:5
   2: <electrs::chain::Network as core::convert::From<&str>>::from
   3: electrs::config::Config::from_args
   4: electrs::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'unsupported Bitcoin network: "liquidtestnet"', src/chain.rs:118:18
```

## `liquidregtest`

I noticed there are network hardcoded to `liquidregtest`, using that in --network flag works till it sync all the headers with Elements node, but has different panic

```sh
Config { log: StdErrLog { verbosity: Trace, quiet: false, show_level: true, timestamp: Off, modules: [], writer: "stderr", color_choice: Never }, network_type: LiquidRegtest, db_path: "./db/liquidregtest", daemon_dir: "/config/liquidregtest", blocks_dir: "/config/liquidregtest/blocks", daemon_rpc_addr: 172.19.0.2:18884, cookie: Some("admin1:123"), electrum_rpc_addr: 0.0.0.0:50001, http_addr: 0.0.0.0:30001, http_socket_file: None, monitoring_addr: 127.0.0.1:44224, jsonrpc_import: false, light_mode: false, address_search: false, index_unspendables: false, cors: Some("*"), precache_scripts: None, utxos_limit: 500, electrum_txs_limit: 500, electrum_banner: "Welcome to electrs-esplora 0.4.1", parent_network: Regtest, asset_db_path: None }
DEBUG - Server listening on 127.0.0.1:44224
INFO - NetworkInfo { version: 180112, subversion: "/Elements Core:0.18.1.12/", relayfee: 0.000001 }
INFO - BlockchainInfo { chain: "liquidtestnet", blocks: 20191, headers: 20191, bestblockhash: "6af6bab05ac56aecb471fd5a23b4b7476d312f919da94cd0d4cfb910df68420d", pruned: false, verificationprogress: 1.0, initialblockdownload: Some(false) }
DEBUG - opening DB at "./db/liquidregtest/newindex/txstore"
DEBUG - Running accept thread
DEBUG - 0 blocks were added
DEBUG - opening DB at "./db/liquidregtest/newindex/history"
DEBUG - 0 blocks were indexed
DEBUG - opening DB at "./db/liquidregtest/newindex/cache"
DEBUG - downloading all block headers up to 6af6bab05ac56aecb471fd5a23b4b7476d312f919da94cd0d4cfb910df68420d
TRACE - downloading 20192 block headers
INFO - hash=6af6bab05ac56aecb471fd5a23b4b7476d312f919da94cd0d4cfb910df68420d height=20191 @ 2021-09-30T15:37:03+00:00 (20192 left to index)
DEBUG - adding transactions from 20192 blocks using BlkFiles
DEBUG - listing block files at "/config/liquidregtest/blocks/blk*.dat"
thread 'blkfiles_fetcher' panicked at 'failed to index 20192 blocks from blk*.dat files', src/new_index/fetch.rs:143:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## `liquid`

Tried also mainnet liquid and still

```sh
Config { log: StdErrLog { verbosity: Trace, quiet: false, show_level: true, timestamp: Off, modules: [], writer: "stderr", color_choice: Never }, network_type: Liquid, db_path: "./db/liquid", daemon_dir: "/config/liquidv1", blocks_dir: "/config/liquidv1/blocks", daemon_rpc_addr: 172.19.0.2:18884, cookie: Some("admin1:123"), electrum_rpc_addr: 0.0.0.0:50001, http_addr: 0.0.0.0:30001, http_socket_file: None, monitoring_addr: 127.0.0.1:34224, jsonrpc_import: false, light_mode: false, address_search: false, index_unspendables: false, cors: Some("*"), precache_scripts: None, utxos_limit: 500, electrum_txs_limit: 500, electrum_banner: "Welcome to electrs-esplora 0.4.1", parent_network: Regtest, asset_db_path: None }

DEBUG - Server listening on 127.0.0.1:34224

INFO - NetworkInfo { version: 180112, subversion: "/Elements Core:0.18.1.12/", relayfee: 0.000001 }

INFO - BlockchainInfo { chain: "liquidtestnet", blocks: 20322, headers: 20322, bestblockhash: "1dc28f5e625a29726a45e15e8093c793c90d7b2d214846bc46f27e898bc15390", pruned: false, verificationprogress: 1.0, initialblockdownload: Some(false) }

DEBUG - Running accept thread

DEBUG - opening DB at "./db/liquid/newindex/txstore"

DEBUG - 0 blocks were added

DEBUG - opening DB at "./db/liquid/newindex/history"

DEBUG - 0 blocks were indexed

DEBUG - opening DB at "./db/liquid/newindex/cache"

DEBUG - downloading all block headers up to 1dc28f5e625a29726a45e15e8093c793c90d7b2d214846bc46f27e898bc15390

TRACE - downloading 20323 block headers

INFO - hash=1dc28f5e625a29726a45e15e8093c793c90d7b2d214846bc46f27e898bc15390 height=20322 @ 2021-09-30T17:48:17+00:00 (20323 left to index)

DEBUG - adding transactions from 20323 blocks using BlkFiles

DEBUG - listing block files at "/config/liquidv1/blocks/blk*.dat"

thread 'blkfiles_fetcher' panicked at 'failed to index 20323 blocks from blk*.dat files', src/new_index/fetch.rs:143:17

stack backtrace:

   0: rust_begin_unwind

             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5

   1: std::panicking::begin_panic_fmt

             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:435:5

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by tiero** [comment]
Thanks @philippem to point me out that we must use the liquid testnet branch :)
