### ISSUE TITLE
thread 'blkfiles_fetcher' panicked

### ISSUE THREAD

**Issue by Trudko** [Blockstream/esplora#353]
Hi, I've downloaded the Esplora, switched to new-index branch and run:
RUST_BACKTRACE=full cargo run --release --bin electrs -- -vvvv  --db-dir /mnt/esplora-electrs-data/ --blocks-dir /mnt/data/bitcoin-core/blocks  --utxos-limit 1000, but I am getting an error:

```
TRACE - reading "/mnt/data/bitcoin-core/blocks/blk02820.dat"
TRACE - parsing 134134776 bytes
TRACE - parsing 50331648 bytes
TRACE - fetched 97 blocks
DEBUG - writing 992397 rows to RocksDB { path: "/mnt/esplora-electrs-data/mainnet/newindex/txstore" }, flush=Disable
TRACE - fetched 30 blocks
DEBUG - writing 1215491 rows to RocksDB { path: "/mnt/esplora-electrs-data/mainnet/newindex/txstore" }, flush=Disable
thread 'blkfiles_fetcher' panicked at 'failed to index 484 blocks from blk*.dat files', src/new_index/fetch.rs:141:17
stack backtrace:
   0:     0x55d3e1cf337a - std::backtrace_rs::backtrace::libunwind::trace::h667de636fd16ec22
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55d3e1cf337a - std::backtrace_rs::backtrace::trace_unsynchronized::hb6272615657d5744
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d3e1cf337a - std::sys_common::backtrace::_print_fmt::h85b0a9a3797c535d
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55d3e1cf337a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h33e1fc29f9141885
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55d3e1b3158f - core::fmt::write::h3b0ec0911656cf8a
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/core/src/fmt/mod.rs:1094:17
   5:     0x55d3e1cf11e4 - std::io::Write::write_fmt::h015d8bf6ff8e54cc
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/io/mod.rs:1584:15
   6:     0x55d3e1d0b855 - std::sys_common::backtrace::_print::hac8aff4fe690f889
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55d3e1d0b855 - std::sys_common::backtrace::print::hcf7ce53748cfb74f
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55d3e1d0b855 - std::panicking::default_hook::{{closure}}::h8e3df13515f3fd66
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/panicking.rs:208:50
   9:     0x55d3e1d0c19a - std::panicking::default_hook::h468fd6be1a9a88b4
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/panicking.rs:225:9
  10:     0x55d3e1d0c19a - std::panicking::rust_panic_with_hook::h37bd253c0dc6b3b6
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/panicking.rs:591:17
  11:     0x55d3e1cf36ad - std::panicking::begin_panic_handler::{{closure}}::hff24a561569e53dd
  12:     0x55d3e1cf361c - std::sys_common::backtrace::__rust_end_short_backtrace::h1e26e0dfac5e461e
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55d3e1d0bb2d - rust_begin_unwind
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/panicking.rs:493:5
  14:     0x55d3e1a69860 - std::panicking::begin_panic_fmt::ha5a9ff8ea450a003
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/panicking.rs:435:5
  15:     0x55d3e1bc94d0 - std::sys_common::backtrace::__rust_begin_short_backtrace::he1ad1a8d94e9ddd0
  16:     0x55d3e1bc8227 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h375241da44aa1d1d
  17:     0x55d3e1cf16c5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h140c34ae15ddced3
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/alloc/src/boxed.rs:1546:9
  18:     0x55d3e1cf16c5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9ea065b6c3e7ab5c
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/alloc/src/boxed.rs:1546:9
  19:     0x55d3e1cf16c5 - std::sys::unix::thread::Thread::new::thread_start::h27ee83c9afd91f53
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/sys/unix/thread.rs:71:17
  20:     0x7fdf87041609 - start_thread
  21:     0x7fdf86e11293 - clone
  22:                0x0 - <unknown>
Aborted (core dumped)
```

Using own bitcoin node 0.22, Ubuntu 20.04.3, always fails at the same block

**Comment by techwise-technologies** [comment]
fwiw i see this error too randomly when i run esplora-electrs, not sure why but when i restart the app it works.
