### ISSUE TITLE
Getting an error when accessing esplora site.

### ISSUE THREAD

**Issue by angelonardone** [Blockstream/esplora#487]
I've installed esplora for testnet on a linux server.
I've  started with:
`export API_URL=http://192.168.10.21:3000/`
and then:
`npm run dev-server`

But when I'm trying to access it from my machine with this:
`192.168.10.21:5000/`
Nothing is displayed on the screen and I'm getting the following message on the server:

`
angelo@bitcointestnet:~/esplora$ npm run dev-server

> esplora@0.1.0 dev-server /home/angelo/esplora
> babel-node dev-server.js

HTTP server running on :::5000
GET / 304 147.923 ms - -
GET /font/inconsolata/index.css 304 4.273 ms - -
GET /bootstrap.min.css 304 5.290 ms - -
GET /light-theme_style.css 304 2.265 ms - -
GET /font/SourceSansPro-Regular.ttf 304 2.355 ms - -
GET /img/favicon.png 304 2.387 ms - -
GET /bootstrap.min.css 304 0.711 ms - -
GET /style.css 304 9.695 ms - -
GET /img/icons/plus.png 304 2.494 ms - -
GET /img/icons/arrow_right_blu.png 304 2.279 ms - -
GET /img/icons/arrow_left_blu.png 304 1.917 ms - -
GET /app.js 500 14.073 ms - 3638
GET /img/icons/copy.png 304 10.588 ms - -
GET /img/icons/menu-logo.svg 304 1.719 ms - -
GET /img/Loading.gif 304 1.696 ms - -
GET /img/icons/search.png 304 1.812 ms - -
Error: Line 26: Unexpected token ...
    at ErrorHandler.constructError (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:5028:27)
    at Parser.unexpectedTokenError (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:1985:39)
    at Parser.throwUnexpectedToken (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:1995:21)
    at Parser.parseObjectPropertyKey (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:2499:33)
    at Parser.parsePropertyPattern (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:3527:25)
    at Parser.parseObjectPattern (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:3538:35)
    at Parser.parsePattern (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:3552:29)
    at Parser.parseLexicalBinding (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:3414:24)
    at Parser.parseBindingList (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:3439:27)
    at Parser.parseLexicalDeclaration (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:3461:34)
    at Parser.parseStatementListItem (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:3385:69)
    at Parser.parseFunctionSourceElements (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:4195:29)
    at Parser.parseAssignmentExpression (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:3286:38)
    at Parser.isolateCoverGrammar (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:2269:37)
    at Parser.parseLexicalBinding (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:3425:34)
    at Parser.parseBindingList (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:3442:29)
    at Parser.parseLexicalDeclaration (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:3461:34)
    at Parser.parseStatementListItem (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:3376:39)
    at Parser.parseScript (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:4723:29)
    at Object.parse (/home/angelo/esplora/client/node_modules/esprima/dist/esprima.js:122:61)
    at transform (/home/angelo/esplora/client/node_modules/envify/custom.js:40:15)
    at Stream.flush (/home/angelo/esplora/client/node_modules/envify/custom.js:81:20)
    at _end (/home/angelo/esplora/client/node_modules/through/index.js:65:9)
    at Stream.stream.end (/home/angelo/esplora/client/node_modules/through/index.js:74:5)
    at DestroyableTransform.onend (/home/angelo/esplora/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:286:20)
    at DestroyableTransform.emit (events.js:203:15)
    at DestroyableTransform.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (/home/angelo/esplora/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
GET /style.css 304 21.852 ms - -
GET /font/inconsolata/index.css 304 0.374 ms - -
GET /light-theme_style.css 304 0.371 ms - -
GET /font/SourceSansPro-Regular.ttf 304 0.742 ms - -
GET /img/icons/plus.png 304 0.729 ms - -
GET /img/icons/arrow_right_blu.png 304 14.418 ms - -
GET /img/icons/arrow_left_blu.png 304 1.597 ms - -
GET /img/icons/copy.png 304 1.634 ms - -
GET /img/icons/menu-logo.svg 304 1.649 ms - -
GET /img/Loading.gif 304 1.906 ms - -
GET /img/icons/search.png 304 0.506 ms - -

`

Any idea what the problem could be?
Thanks.
angelo

**Comment by bperin** [comment]
same error
