### ISSUE TITLE
Continuous npm error while sync bitcoin chain

### ISSUE THREAD

**Issue by BoGnY** [Blockstream/esplora#83]
Hi guys, I'm starting to use esplora, I have followed all instructions, but when I start the command
```bash
docker run -p 8080:80 \
           --volume $PWD/data_bitcoin_mainnet:/data \
           --rm -i -t esplora \
           bash -c "/srv/explorer/run.sh bitcoin-mainnet explorer"
```
during the syncronization, I get this error very frequently:
```log
2019-04-29T14:46:31Z UpdateTip: new best=00000000000004200ad0beb62570ecd9359e0bda65984a6f5195bbc28c639db2 height=201152 version=0x00000001 log2_work=68.782408                                                                               tx=7526844 date='2012-09-30T00:11:19Z' progress=0.019395 cache=363.2MiB(2710494txo)
2019-04-29T14:46:31Z UpdateTip: new best=00000000000004e83bdf7f2105ba1d11e98f8531f7ba3605d5b28844789e8f6f height=201153 version=0x00000001 log2_work=68.782443                                                                               tx=7526853 date='2012-09-30T00:27:23Z' progress=0.019395 cache=363.2MiB(2710495txo)
2019-04-29T14:46:31Z UpdateTip: new best=00000000000000e02b408d72c3b42fae34800ff933f111c69539f14d492c5b03 height=201154 version=0x00000001 log2_work=68.782478                                                                               tx=7526954 date='2012-09-30T00:31:54Z' progress=0.019395 cache=363.2MiB(2710531txo)
module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: libjpeg.so.8: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/explorer/source/client/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
2019-04-29T14:46:31Z UpdateTip: new best=00000000000001f82a44ce57f652f40179d9178734afa00b1771397b1a49cfa1 height=201155 version=0x00000001 log2_work=68.782513                                                                               tx=7527171 date='2012-09-30T00:37:42Z' progress=0.019396 cache=363.2MiB(2710587txo)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! esplora-serverside-render@0.1.0 start: `./start.sh "bitcoin-mainnet"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the esplora-serverside-render@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-04-29T14:46:31Z UpdateTip: new best=00000000000000a09a8d8f8ac15d1e9a6dbf663b2e4b489d0c227a260edeefd8 height=201156 version=0x00000002 log2_work=68.782548                                                                               tx=7527389 date='2012-09-30T00:40:05Z' progress=0.019397 cache=363.2MiB(2710359txo)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-29T14_46_31_242Z-debug.log
2019-04-29T14:46:31Z UpdateTip: new best=000000000000057696620269b564c4956d3b3d57dd2d9c90c34e7586bf037ff8 height=201157 version=0x00000002 log2_work=68.782583                                                                               tx=7527451 date='2012-09-30T01:01:24Z' progress=0.019397 cache=363.2MiB(2710614txo)
2019-04-29T14:46:31Z UpdateTip: new best=00000000000002ebdb65e8d3da2e1786da451cb833f637d5e1b3aade1dfd1387 height=201158 version=0x00000002 log2_work=68.782618                                                                               tx=7527524 date='2012-09-30T00:49:51Z' progress=0.019397 cache=363.2MiB(2710630txo)
2019-04-29T14:46:31Z UpdateTip: new best=000000000000033e63889cc0d770aeca887fce0c046e36ad6402f69c8383bf18 height=201159 version=0x00000001 log2_work=68.782653                                                                               tx=7527530 date='2012-09-30T01:28:22Z' progress=0.019397 cache=363.2MiB(2710623txo)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! esplora@0.1.0 prerender-server: `cd prerender-server && npm start "--cluster" "bitcoin-mainnet"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the esplora@0.1.0 prerender-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-29T14_46_31_257Z-debug.log
2019-04-29T14:46:31Z UpdateTip: new best=00000000000003f8d0917dddc502943639b7cc260b09a9ef000b1e5eb0027a14 height=201160 version=0x00000002 log2_work=68.782688                                                                               tx=7527945 date='2012-09-30T01:35:14Z' progress=0.019398 cache=363.2MiB(2710824txo)
2019-04-29T14:46:31Z UpdateTip: new best=00000000000002f6de4e41ed93290ed0322db32dddcc25262173b403f5ed17ee height=201161 version=0x00000001 log2_work=68.782723                                                                               tx=7528130 date='2012-09-30T01:59:36Z' progress=0.019399 cache=363.2MiB(2710942txo)
2019-04-29T14:46:31Z UpdateTip: new best=00000000000000eade414e1df2f56e3389d0e85bc7e0fd2d169fb355488fe2ca height=201162 version=0x00000001 log2_work=68.782758                                                                               tx=7528222 date='2012-09-30T02:00:36Z' progress=0.019399 cache=363.2MiB(2710975txo)
```

Is this normal??
Thanks

**Comment by BoGnY** [comment]
Ok, I've found that Debian (as reported [here](https://github.com/neocotic/qrious/issues/106#issuecomment-374010500)), when installing `libjpeg-dev` package (in [Dockerfile](https://github.com/Blockstream/esplora/blob/master/Dockerfile#L10)), it install `libjpeg.so.62` lib, and not as in Ubuntu that the same package install `libjpeg.so.8`..

I'm searching how install `libjpeg.so.8` on Debian.

**Comment by shesek** [comment]
Are you still running into this? I've been using the docker image successfully on both debian and ubuntu as the host.

**Comment by shesek** [comment]
Hi @BoGnY, I'm closing this for now, please report back if you're still having trouble setting this up.
